using ExercicioLogica;
using ExercicioLogica.exemploAula;
using ExercicioLogica.listaIAGemini;
using ExercicioLogica.manzano46;
using ExercicioLogica.manzano50;
using ExercicioLogica.manzano66;
using System;

//Ex01Manzano46.Main(args);
//Ex02Manzano46.Main(args);
//Ex03Manzano46.Main(args);
//Ex01Manzano50.Main(args);
//Ex02Manzano50.Main(args);
//Ex03Manzano50.Main(args);
//Ex04Manzano50.Main(args);
//ExFor.Main(args);
//Temporizador.Main(args);
//Cronometro.Main(args);
//Ex01Manzano66.Main(args);
//Ex02Manzano66.Main(args);
//Ex04Manzano66.Main(args);
//Ex05Manzano66.Main(args);
//Ex06Manzano66.Main(args);
//Ex07Manzano66.Main(args);
//Ex08Manzano66.Main(args);
//FloatDouble.Main(args);
//FloatDouble02.Main(args);
//BooleanEx.Main(args);
//CharString.Main(args);
//ConversaoExplicita.Main(args);
//ConversaoTipo.Main(args);
//ExemploMatematica.Main(args);
//ManipulandoVariavel.Main(args);
//EspecialCaracter.Main(args);
//BooleanEx.Main(args);
//Continue.Main(args);
//BreakContinue.Main(args);
//VetorMatriz.Main(args);
//TiposVetores.Main(args);
//ForEach.Main(args);
//ForEachShort.Main(args);
//ForEachShort02.Main(args);
//LinqEx01.Main(args);
//Matriz2D.Main(args);
//ForEachMatriz.Main(args);
//Ex01listaIAGemini.Main(args);
//MetodosCSharp.Main(args);
//CriandoMetodosComParamentros.Main(args);
//CriandoMetodosComMultiplosParamentros.Main(args);
//MetodosComValorPadrao.Main(args);
//MetodoRetornarValor.Main(args);
//MetodoArgumentoNomeadoAtribuindoValor.Main(args);
//MetodoSobrecarga.Main(args);
//MetodoSobrecarga01.Main(args);
//Professor.Main(args);
//Computador.Main(args);
//Professor01.Main(args);
Feira.Main(args);